- docs/security.md
> Created docs folder.  Updated security.md file.

- src/VersionChecker.ts
Signed-off-by: Mike <michael.johanson@intel.com>
> fix(protocol-version)--null-not-being-checked

- package-lock.json
- package.json
Signed-off-by: Mike <michael.johanson@intel.com>
> fix(deps): missing atob dependency in prod

- src/DataProcessor.ts
- src/Index.ts
- src/Logger.ts
- src/RCS.Config.ts
- src/Validator.ts
- src/WSManProcessor.ts
- src/WebSocketListener.ts
- src/actions/ACMActivator.ts
- src/models/Rcs.ts
- src/routes/admin/index.ts
Signed-off-by: Mike <michael.johanson@intel.com>
> refactor(lint): misc rules

- .github/workflows/docker-image-ci.yml
Signed-off-by: Mike <michael.johanson@intel.com>
> ci: add docker push to ci

- swagger.yaml
Updates to the swagger.yaml
- updated general description with examples
- removed APIKEY references
- fixed POST and PATCH calls with updated input examples
- fixed success responses with updated response examples
- removed network config Patch and Delete as these are currently not active
- updated version response
- added descriptions to all API calls
> fix(swagger): updated API documentation

- data/init.sql
- src/RCS.Config.ts
- src/repositories/ciraConfigs.ts
- src/repositories/mapToCiraConfig.ts
- src/routes/admin/ciraconfig/ciraValidator.ts
- src/routes/admin/ciraconfig/createCiraConfig.ts
- src/routes/admin/ciraconfig/editCiraConfig.ts
- src/test/collections/rps.postman_collection.json
BREAKING CHANGE: DB Schema changes for CIRA config to accept both static and dynamic passwords.
> feat(api): cira config will accept static or generates dynamic password

- data/init.sql
- scripts/kubernetes/azure-rps.yaml
- src/ProfileManager.ts
- src/interfaces/IProfileManager.ts
- src/models/Rcs.ts
- src/repositories/mapToProfile.ts
- src/repositories/profiles.ts
- src/test/helper/data.json
- src/test/profileManager.test.ts
- src/test/validator.test.ts
- swagger.yaml
BREAKING CHANGE: removed configuration_script column from profiles db
> refactor(db): removed unused configuration script from profiles

- src/models/Rcs.ts
- src/repositories/ciraConfigs.ts
- src/repositories/domains.ts
- src/repositories/interfaces/ICiraConfigDb.ts
- src/repositories/interfaces/IDomainsDb.ts
- src/repositories/interfaces/IProfilesDb.ts
- src/repositories/interfaces/IWirelessProfilesDB.ts
- src/repositories/profiles.ts
- src/repositories/wirelessProfiles.ts
- src/routes/admin/ciraconfig/all.ts
- src/routes/admin/ciraconfig/index.ts
- src/routes/admin/domains/all.ts
- src/routes/admin/domains/index.ts
- src/routes/admin/profiles/all.ts
- src/routes/admin/profiles/index.ts
- src/routes/admin/validator.ts
- src/routes/admin/wireless/all.ts
- src/routes/admin/wireless/index.ts
- src/test/collections/rps.postman_collection.json
- src/test/profileManager.test.ts
- src/utils/constants.ts
closes [AB#2763](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2763) [AB#2765](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2765)
> feat(api): added pagination

- src/RCS.Config.ts
- src/Validator.ts
- src/WebSocketListener.ts
- src/actions/Activator.ts
- src/actions/CIRAConfigurator.ts
- src/actions/Deactivator.ts
- src/actions/NetworkConfigurator.ts
- src/test/activator.test.ts
- src/test/deactivator.test.ts
- src/test/networkConfigurator.test.ts
closes [AB#2776](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2776)
> fix(activation): updated client response message to json

- .rpsrc
Related work items: [AB#3417](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/3417)
> refactor(sslpostgres): removed password and enabled ssl

- src/repositories/wirelessProfiles.ts
- src/routes/admin/ciraconfig/deleteCiraConfig.ts
- src/routes/admin/wireless/deleteProfile.ts
- src/test/collections/rps.postman_collection.json
closes [AB#2952](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2952)
> fix(errors): return error name while delete request fails

- src/Validator.ts
> fix(device): update tags execute after device exists check

- package.json
> build(version): bump to v2.1.0

- src/DataProcessor.ts
- src/Validator.ts
- src/WebSocketListener.ts
- src/actions/Activator.ts
- src/models/RCS.Config.ts
- src/test/updateAMTAdminPassword.test.ts
- src/utils/maintenance/updateAMTAdminPassword.ts
> feat(activation): add already activated device to toolkit

- .github/workflows/node.js.yml
> ci(workflow): optimizes node CI

- .github/workflows/node.js.yml
- .gitignore
- jest.config.js
- package-lock.json
- package.json
> ci(test): add unit test output report

- src/middleware/validate.test.ts
- src/test/helper/jest.ts
Adding coverage to middleware/validate.ts
Adding jest.ts under test/helpers for createSpyObj function
[AB#5614](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5614)
Adding uni test
Just adding unit test and a test helper
n/a
> test(middleware): Adding unit test to middleware

- src/routes/admin/version/getVersion.test.ts
- src/routes/admin/version/index.test.ts
Adding unit test for routes/admin/version folder
[AB#5615](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5615)
Adding unit test
Just adding unit test
n/a
> test(version): Adding test to version

- src/utils/parseEnvValue.test.ts
Adding unit test to utils/parseEnvValue.ts
[AB#5617](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5617)
> test(utils): Adding test to parseEnvValue

- src/routes/admin/index.test.ts
Adding unit test for routes/admin/index.ts
[AB#5622](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5622)
Adding unit test
Adding unit test
n/a
> test(routes): Adding unit test to admin index

- src/routes/admin/health/getHealth.test.ts
- src/routes/admin/health/index.test.ts
Adding unit test for routes/health folder
[AB#5621](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5621)
Adding unit test
Just adding unit test
n/a
> test(health): Adding unit test to health

- src/routes/index.test.ts
Adding unit test for routes/index.ts
[AB#5624](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5624)
Adding unit test
Just adding unit test
n/a
> test(routes): Adding unit test for index

- package-lock.json
- package.json
- src/ClientActions.ts
- src/DataProcessor.ts
- src/HttpHandler.test.ts
- src/HttpHandler.ts
- src/actions/Deactivator.ts
- src/actions/deactivator.test.ts
- src/dataProcessor.test.ts
- src/interfaces/IExecutor.ts
- src/utils/parseWSManResponseBody.test.ts
- src/utils/parseWSManResponseBody.ts
[AB#5529](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5529)
[AB#5517](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5517)
> refactor(deactivator): adds wmsan_messages and unit tests

- src/ClientActions.ts
- src/DataProcessor.ts
- src/HttpHandler.test.ts
- src/HttpHandler.ts
- src/WebSocketListener.ts
- src/actions/Activator.ts
- src/actions/Deactivator.ts
- src/actions/Maintenance.ts
- src/actions/activator.test.ts
- src/actions/deactivator.test.ts
- src/actions/maintenance.test.ts
- src/dataProcessor.test.ts
- src/models/RCS.Config.ts
- src/utils/maintenance/setMEBXPassword.test.ts
- src/utils/maintenance/setMEBXPassword.ts
- src/utils/maintenance/synchronizeTime.test.ts
- src/utils/maintenance/synchronizeTime.ts
- src/utils/maintenance/updateAMTAdminPassword.test.ts
- src/utils/maintenance/updateAMTAdminPassword.ts
- src/webSocketListener.test.ts
>  refactor(maintenance): adds wmsan_messages and unit tests

- package-lock.json
- package.json
- src/ClientActions.ts
- src/WebSocketListener.ts
- src/actions/Deactivator.ts
- src/actions/NetworkConfigurator.ts
- src/actions/activator.test.ts
- src/actions/deactivator.test.ts
- src/actions/networkConfigurator.test.ts
[AB#5526](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5526)
[AB#5533](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5533)
> refactor(network): adds wsman-messages and unittests

- package-lock.json
- package.json
> build(deps): remove request and eslint-plugin-standard

- package-lock.json
- package.json
- src/actions/CIRAConfigurator.ts
- src/actions/NetworkConfigurator.ts
- src/actions/TLSConfigurator.ts
- src/actions/networkConfigurator.test.ts
> refactor(wifi): ensure wifi configuration completes successfully

- package-lock.json
- package.json
- src/DataProcessor.ts
- src/HttpHandler.ts
- src/actions/Activator.ts
- src/actions/CIRAConfigurator.ts
- src/actions/NetworkConfigurator.ts
- src/actions/TLSConfigurator.ts
- src/actions/ciraConfigurator.test.ts
- src/actions/networkConfigurator.test.ts
- src/actions/tlsConfigurator.test.ts
- src/models/RCS.Config.ts
- src/utils/maintenance/synchronizeTime.ts
> feat(cira): adds setting MpsType to 'both'

- src/routes/admin/profiles/amtProfileValidator.ts
- src/test/collections/rps.postman_collection.json
> fix(cira): removes DHCP check

- src/actions/NetworkConfigurator.ts
> fix(network): handles when only one ethernet port setting

- .github/workflows/semantic.yml
> ci: swap our semantic pull request bot for Github Action

- .github/workflows/semantic.yml
> ci(lint): adds semantic commit lints

- src/Validator.ts
- src/WebSocketListener.ts
- src/validator.test.ts
- src/webSocketListener.test.ts
> refactor(websockets): add input validation checks

- src/routes/admin/health/getHealth.test.ts
- src/routes/admin/health/getHealth.ts
- src/utils/constants.ts
> fix(healthcheck): handle vault missing

- src/actions/NetworkConfigurator.ts
Co-authored-by: Mike <michael.johanson@intel.com>
> fix(network): handles put response for AMT_generalsettings

- src/Validator.ts
- src/validator.test.ts
> fix(validator): remove uuid format check

- data/init.sql
- src/actions/activator.test.ts
- src/actions/ciraConfigurator.test.ts
- src/actions/networkConfigurator.test.ts
- src/data/postgres/tables/profiles.test.ts
- src/data/postgres/tables/profiles.ts
- src/models/index.ts
- src/profileManager.test.ts
- src/routes/admin/profiles/amtProfileValidator.test.ts
- src/routes/admin/profiles/amtProfileValidator.ts
- src/routes/admin/profiles/create.test.ts
- src/routes/admin/profiles/create.ts
- src/routes/admin/profiles/edit.test.ts
- src/routes/admin/profiles/edit.ts
- src/test/collections/rps.postman_collection.json
- src/utils/maintenance/updateAMTAdminPassword.test.ts
[AB#4345](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/4345)
Added user consent, kvm, sol and ider configurations to AMT profile
> feat(profile): added user consent, kvm, sol and ider to AMT profile

- .github/workflows/node.js.yml
> ci: remove node 12 and add 18 for build

- .github/workflows/api-test.yml
- src/test/collections/data/rps_security_api_test.data.json
- src/test/collections/rps_security_api_test.postman_collection.json
> test(api): automated rps postman verb tests via newman

- src/actions/NetworkConfigurator.ts
- src/actions/networkConfigurator.test.ts
- src/models/RCS.Config.ts
closes [AB#12419](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/12419)
> feat(network): support WiFi only activation and provisioning

- src/actions/CIRAConfigurator.ts
> fix(cira): added an error message when failed to remove certs

- .github/workflows/api-test.yml
- .github/workflows/codeql-analysis.yml
> ci(postman): add test result output in json and junit

- .github/workflows/api-test.yml
- .github/workflows/node.js.yml
> ci: rename test output files

- CHANGELOG.md
- package-lock.json
- package.json
> chore: update changelog and bump package.json version for release

- src/routes/admin/domains/create.test.ts
- src/routes/admin/domains/create.ts
- src/routes/admin/profiles/create.test.ts
- src/routes/admin/profiles/create.ts
> fix(api): create endpoints now rollback db if vault fails

- src/DataProcessor.ts
- src/Index.ts
- src/models/RCS.Config.ts
- src/stateMachines/activation.test.ts
- src/stateMachines/activation.ts
> refactor(activation): adds xstate framework for activation

- src/stateMachines/activation.test.ts
[AB#13368](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/13368)
[AB#13369](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/13369)
> refactor(test): adds unit tests to activation state machine

- src/actions/Activator.ts
- src/models/index.ts
- src/profileManager.test.ts
- src/stateMachines/activation.ts
- src/test/helper/Config.ts
- src/utils/maintenance/setMEBXPassword.ts
- src/utils/maintenance/updateAMTAdminPassword.ts
- src/utils/mqtt.test.ts
> refactor(config): remove unnused amtusername

- src/stateMachines/featuresConfiguration.ts
> fix(profile features): corrected CIM_KVMRedirection enum comparison

- src/ClientActions.ts
- src/DataProcessor.ts
- src/stateMachines/ciraConfiguration.ts
- src/stateMachines/deactivation.test.ts
- src/stateMachines/featuresConfiguration.test.ts
- src/stateMachines/maintenance.test.ts
- src/stateMachines/maintenance.ts
- src/stateMachines/networkConfiguration.test.ts
- src/stateMachines/networkConfiguration.ts
> refactor(maintenance): uses xstate for maintenance tasks 

- package-lock.json
- src/DataProcessor.ts
- src/dataProcessor.test.ts
- src/models/RCS.Config.ts
- src/stateMachines/activation.test.ts
- src/stateMachines/activation.ts
- src/stateMachines/ciraConfiguration.test.ts
- src/stateMachines/ciraConfiguration.ts
- src/stateMachines/error.test.ts
- src/stateMachines/error.ts
- src/stateMachines/networkConfiguration.test.ts
- src/stateMachines/networkConfiguration.ts
- src/stateMachines/unconfiguration.test.ts
- src/stateMachines/unconfiguration.ts
> refactor(reconfigure): updated to reconfigure a device

- src/stateMachines/activation.ts
- src/stateMachines/networkConfiguration.test.ts
- src/stateMachines/networkConfiguration.ts
> refactor(status): formats network status message

- src/stateMachines/activation.test.ts
- src/stateMachines/activation.ts
> refactor(activation): adds specific error message to provision cert

- src/stateMachines/deactivation.test.ts
- src/stateMachines/deactivation.ts
> refactor(deactivation): adds checks for secret provider responses

- src/stateMachines/deactivation.test.ts
- src/stateMachines/deactivation.ts
- src/stateMachines/error.ts
> refactor(deactivation): update error message

- CHANGELOG.md
- package.json
> docs: updates changelog for v2.5.0

- package-lock.json
- src/routes/admin/version/get.test.ts
- src/routes/admin/version/get.ts
- src/test/collections/rps.postman_collection.json
- src/utils/constants.ts
Adds appversion to version API call
> feat(appversion): adds appversion to version api

- src/routes/admin/version/get.test.ts
- src/routes/admin/version/get.ts
- src/utils/ClientResponseMsg.ts
- src/utils/constants.ts
> test(getVersion): fixes getVersion tests

- .github/workflows/api-test.yml
- .github/workflows/changelog.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-image-ci.yml
- .github/workflows/docker-image.yml
- .github/workflows/node.js.yml
- .github/workflows/semantic.yml
- docker-compose.yml
> ci(actions): update to actions/checkout@v3

- .github/workflows/issueSync.yml
> ci(ab-sync): update action to v2.1

- src/DataProcessor.ts
- src/Validator.ts
- src/WebSocketListener.ts
- src/dataProcessor.test.ts
- src/models/RCS.Config.ts
- src/stateMachines/activation.test.ts
- src/stateMachines/activation.ts
- src/stateMachines/ciraConfiguration.test.ts
- src/stateMachines/deactivation.test.ts
- src/stateMachines/error.test.ts
- src/stateMachines/featuresConfiguration.test.ts
- src/stateMachines/featuresConfiguration.ts
- src/stateMachines/networkConfiguration.test.ts
- src/stateMachines/unconfiguration.test.ts
- src/validator.test.ts
> fix(activation): adds mebx password to secret provider on reconfigure

- src/stateMachines/networkConfiguration.test.ts
- src/stateMachines/networkConfiguration.ts
[AB#14434](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/14434)
> refactor(network):  by default enables local profile synchronization for wifi

- CHANGELOG.md
- package-lock.json
- package.json
> build: bump version for v2.6.0

- .github/workflows/projectsSync.yaml
> ci: add projects sync to rps

- .github/workflows/azureBoardsSync.yml
> ci: changes type from "Bug" to "User Story"

- .github/workflows/azureBoardsSync.yml
> ci(azureBoardsSync): change wit to "Product Backlog Item"

- .github/workflows/azureBoardsSync.yml
> ci(azureBoardsSync): remove github personal access token

- .github/commitlint.config.js
- .github/workflows/semantic.yml
- CONTRIBUTING.MD
> ci: update ci semantic check

- package-lock.json
- package.json
- src/Index.ts
- src/index.test.ts
Closes: [AB#14653](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/14653)
> feat(health): add waits for db and vault to be available to respond

- .rpsrc
- src/CommandParser.ts
- src/DataProcessor.ts
- src/commandParser.test.ts
- src/dataProcessor.test.ts
- src/stateMachines/maintenance.test.ts
- src/stateMachines/maintenance.ts
- src/stateMachines/syncHostName.test.ts
- src/stateMachines/syncHostName.ts
> feat(maintenance): maintenance sync hostname information

- src/Index.ts
> refactor: startup promises are no longer ignored with void

- CHANGELOG.md
- package-lock.json
- package.json
> build: update package.json to v2.7.0

- src/stateMachines/deactivation.test.ts
- src/stateMachines/deactivation.ts
> fix: if MPS isn't available, RPS should not error when attempting

- jest.config.js
- src/CommandParser.ts
- src/Index.ts
- src/data/postgres/tables/profileWifiConfigs.ts
- src/index.test.ts
- src/middleware/custom/example.ts
- src/utils/PasswordHelper.ts
- src/utils/mqtt.test.ts
- src/webSocketListener.test.ts
- tsconfig.json
closes [AB#15528](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/15528)
> feat(api): add support for custom middleware

- src/Configurator.ts
- src/Index.ts
- src/Validator.ts
- src/dataProcessor.test.ts
- src/repositories/factories/amtDeviceVaultRepository.test.ts
- src/routes/admin/health/getHealth.test.ts
- src/routes/admin/health/getHealth.ts
- src/routes/admin/profiles/create.test.ts
- src/stateMachines/activation.test.ts
- src/stateMachines/activation.ts
- src/stateMachines/amtPassword.test.ts
- src/stateMachines/ciraConfiguration.test.ts
- src/stateMachines/ciraConfiguration.ts
- src/stateMachines/deactivation.test.ts
- src/stateMachines/deactivation.ts
- src/stateMachines/maintenance.test.ts
- src/stateMachines/networkConfiguration.test.ts
- src/stateMachines/networkConfiguration.ts
- src/stateMachines/syncHostName.ts
- src/stateMachines/unconfiguration.test.ts
- src/stateMachines/unconfiguration.ts
- src/utils/Environment.ts
- src/utils/SecretManagerService.ts
- src/utils/secretManagerService.test.ts
- src/validator.test.ts
> refactor: align environment usage to match MPS

- package-lock.json
- package.json
- src/HttpHandler.test.ts
- src/models/RCS.Config.ts
- src/models/WSManResponse.ts
- src/stateMachines/activation.test.ts
- src/stateMachines/activation.ts
- src/stateMachines/amtPassword.ts
- src/stateMachines/ciraConfiguration.ts
- src/stateMachines/deactivation.test.ts
- src/stateMachines/deactivation.ts
- src/stateMachines/featuresConfiguration.ts
- src/stateMachines/networkConfiguration.test.ts
- src/stateMachines/networkConfiguration.ts
- src/stateMachines/syncHostName.ts
- src/stateMachines/syncIP.ts
- src/stateMachines/timeMachine.ts
- src/stateMachines/tls.test.ts
- src/stateMachines/tls.ts
- src/stateMachines/unconfiguration.test.ts
- src/stateMachines/unconfiguration.ts
> build(deps): update wsman-messages to 5.0.0

- .github/workflows/changelog.yml
> ci: fixed changelog build

- data/init.sql
- src/Index.ts
- src/ProfileManager.ts
- src/WSEnterpriseAssistantListener.test.ts
- src/WSEnterpriseAssistantListener.ts
- src/data/postgres/tables/profiles.test.ts
- src/data/postgres/tables/profiles.ts
- src/models/RCS.Config.ts
- src/models/index.ts
- src/routes/admin/profiles/amtProfileValidator.test.ts
- src/routes/admin/profiles/amtProfileValidator.ts
- src/routes/admin/profiles/common.ts
- src/routes/admin/profiles/create.test.ts
- src/routes/admin/profiles/create.ts
- src/routes/admin/profiles/edit.test.ts
- src/routes/admin/profiles/edit.ts
- src/stateMachines/common.test.ts
- src/stateMachines/common.ts
- src/stateMachines/tls.test.ts
- src/stateMachines/tls.ts
- src/test/collections/rps.postman_collection.json
> feat(activation): add TLS CA Cert generation with MSFT CA

- CHANGELOG.md
- package.json
> build: update package.json to v2.8.0

- src/routes/admin/ciraconfig/ciraValidator.ts
- src/test/collections/rps.postman_collection.json
- src/test/collections/rps.postman_environment.json
> refactor: check cira config name for special characters

- src/ProfileManager.ts
- src/interfaces/ISecretManagerService.ts
- src/routes/admin/ciraconfig/all.ts
- src/routes/admin/ciraconfig/create.ts
- src/routes/admin/ciraconfig/edit.ts
- src/routes/admin/ciraconfig/get.ts
- src/secrets/vault/index.ts
- src/stateMachines/activation.ts
- src/stateMachines/amtPassword.ts
- src/stateMachines/ciraConfiguration.test.ts
- src/stateMachines/ciraConfiguration.ts
- src/test/collections/rps.postman_collection.json
- src/utils/PasswordHelper.ts
- src/utils/constants.ts
> fix: CIRA static password being saved to DB

- src/stateMachines/activation.ts
- src/stateMachines/deactivation.ts
- src/stateMachines/error.ts
> fix: RPC - RPS invalid password error message handling

- jest.config.js
- src/profileManager.test.ts
- src/stateMachines/deactivation.test.ts
- src/stateMachines/networkConfiguration.test.ts
- src/stateMachines/tls.test.ts
- src/stateMachines/unconfiguration.test.ts
- src/validator.test.ts
> test: use fake timers and clean up

- CHANGELOG.md
- package-lock.json
- package.json
> build: update package.json to v2.9.0

- src/utils/passwordValidationUtils.ts
> fix: address hyphen in passwordValidation to be correct

- .github/workflows/codeql-analysis.yml
- .github/workflows/codeql-report.yml
- README.md
> ci: break out codeql report into separate workflow

- src/stateMachines/common.test.ts
- src/stateMachines/common.ts
- src/stateMachines/tls.test.ts
- src/stateMachines/tls.ts
- src/utils/constants.ts
> fix: added timer on ea response calls

- src/routes/admin/wireless/create.test.ts
- src/routes/admin/wireless/create.ts
> fix: not saving passphrase in vault

- .github/workflows/node.js.yml
> ci(deps): bump codecov to v3.1.3

- src/data/postgres/tables/profileWifiConfigs.test.ts
- src/data/postgres/tables/profiles.test.ts
- src/data/postgres/tables/profiles.ts
- src/interfaces/database/IProfileWifiConfigsDb.ts
- src/routes/admin/profiles/edit.test.ts
- src/routes/admin/profiles/edit.ts
> fix: handle multitenancy for profiles with wifi 

- src/models/RCS.Config.ts
- src/stateMachines/activation.ts
- src/stateMachines/unconfiguration.test.ts
- src/stateMachines/unconfiguration.ts
- src/stateMachines/wifiNetworkConfiguration.test.ts
- src/stateMachines/wifiNetworkConfiguration.ts
- src/stateMachines/wiredNetworkConfiguration.ts
> feat: implemented configuration of  8021x wireless profiles on AMT

- CHANGELOG.md
- package-lock.json
- package.json
> build: update package.json to v2.10.0

- src/stateMachines/activation.ts
- src/stateMachines/amtPassword.ts
- src/stateMachines/deactivation.ts
- src/stateMachines/maintenance.ts
- src/stateMachines/networkConfiguration.ts
- src/stateMachines/syncHostName.ts
- src/stateMachines/syncIP.ts
- src/stateMachines/tls.ts
- src/stateMachines/unconfiguration.ts
- src/stateMachines/wifiNetworkConfiguration.ts
- src/stateMachines/wiredNetworkConfiguration.ts
Addresses https://xstate.js.org/docs/guides/actions.html#send-action
> refactor(state-machine): replace deprecated send with sendTo

- .github/workflows/release.yml
- .releaserc.json
> build: automated versioning and publishing

- CHANGELOG.md
- package-lock.json
- package.json
> build: update version and changelog for v2.11.0

- .github/workflows/release.yml
> build: updated semantic release

- src/stateMachines/wifiNetworkConfiguration.test.ts
- src/stateMachines/wifiNetworkConfiguration.ts
> fix: adds check for unsupported encryption methods  

- CHANGELOG.md
- package-lock.json
- package.json
> build: update version and changelog to v2.11.1

- .github/workflows/release.yml
- .releaserc.json
> ci: adds github release to semantic release

- src/stateMachines/maintenance/changePassword.test.ts
- src/stateMachines/maintenance/changePassword.ts
> fix: refresh amt pw after pw change

- .releaserc.json
> ci: add git to publish package.json version

- src/DataProcessor.ts
- src/dataProcessor.test.ts
- src/stateMachines/activation.test.ts
- src/stateMachines/activation.ts
> feat: support device friendly name

- CHANGELOG.md
- package-lock.json
- package.json
> build: update version and changelog to v2.12.0

- .github/workflows/node.js.yml
> ci: remove nodejs 14 from build add 20.x

- src/middleware/custom/example.ts
> fix: ensure req.tenantId is defaulted to blank

- CHANGELOG.md
- package-lock.json
- package.json
> build: updates package.json and changelog to v2.12.1

- docker-compose.yml
> build:  update vault for docker compose

- src/routes/admin/ieee8021x/constants.ts
- src/stateMachines/activation.ts
- src/stateMachines/enterpriseAssistant.test.ts
- src/stateMachines/enterpriseAssistant.ts
- src/stateMachines/networkConfiguration.test.ts
- src/stateMachines/networkConfiguration.ts
- src/stateMachines/tls.test.ts
- src/stateMachines/tls.ts
- src/stateMachines/unconfiguration.test.ts
- src/stateMachines/unconfiguration.ts
- src/stateMachines/wifiNetworkConfiguration.test.ts
- src/stateMachines/wifiNetworkConfiguration.ts
- src/stateMachines/wiredNetworkConfiguration.test.ts
- src/stateMachines/wiredNetworkConfiguration.ts
- src/test/collections/rps.postman_collection.json
> feat: adds MSCHAPv2 configuration for wired and wireless

- src/stateMachines/unconfiguration.test.ts
- src/stateMachines/wifiNetworkConfiguration.test.ts
- src/stateMachines/wifiNetworkConfiguration.ts
> fix: upated network status message

- package-lock.json
- package.json
> build: bump @open-amt-cloud-toolkit/wsman-messages to 5.5.0

- CHANGELOG.md
- package-lock.json
- package.json
> build: update v2.15.0 in package.json and changelog

- Dockerfile
> build: update docker image dependencies

- .github/workflows/codeql-analysis.yml
> ci: add codeql report

- .github/workflows/trivy-scan.yml
> ci: publish trivy results to github

- .github/workflows/codeql-analysis.yml
> ci: continue on error of codeql analysis report steps

- .github/workflows/trivy-scan.yml
> ci: add trivy upload scan always

- src/stateMachines/activation.ts
> refactor: remove double promises

- .releaserc.json
> ci: update plugins for semantic release

- src/stateMachines/unconfiguration.ts
> fix: adds shouldRetry guards

- .github/workflows/release.yml
- .releaserc.json
> ci: add release tag to docker image

- src/stateMachines/unconfiguration.test.ts
- src/stateMachines/unconfiguration.ts
> fix(state-machine): unconfigure continues on error for TLS deletions

- data/init.sql
> fix: allow same domain suffix across tenants

- src/stateMachines/activation.ts
> fix: store dnssuffix into db

- src/CommandParser.ts
- src/DataProcessor.ts
- src/commandParser.test.ts
- src/dataProcessor.test.ts
- src/stateMachines/maintenance/maintenance.test.ts
- src/stateMachines/maintenance/maintenance.ts
- src/stateMachines/maintenance/syncDeviceInfo.test.ts
- src/stateMachines/maintenance/syncDeviceInfo.ts
> feat: add device info maintenance

- .github/workflows/release.yml
- Dockerfile
> ci: update to node 20

- CHANGELOG.md
- package-lock.json
- package.json
> fix: package version and changelog

- .releaserc.json
> ci: updated repo for release automation

- .github/workflows/release.yml
> ci: adds persist-credentials:false to checkout

- CHANGELOG.md
- data/init.sql
- package-lock.json
- package.json
- src/data/postgres/tables/profiles.test.ts
- src/data/postgres/tables/profiles.ts
- src/models/index.ts
- src/routes/admin/profiles/amtProfileValidator.ts
- src/routes/admin/profiles/edit.ts
- src/stateMachines/networkConfiguration.ts
- src/stateMachines/wifiNetworkConfiguration.test.ts
- src/stateMachines/wifiNetworkConfiguration.ts
- src/test/collections/rps.postman_collection.json
> feat: add wifi sync enable to profiles table

- package-lock.json
- package.json
- src/stateMachines/maintenance/changePassword.test.ts
- src/stateMachines/maintenance/changePassword.ts
> fix: message when changing password on TLS device

- CHANGELOG.md
- package-lock.json
- package.json
> ci: update package.json and changelog

- .github/workflows/node.js.yml
> ci: remove node 16 from build

- package-lock.json
- package.json
> build(deps-dev): update jest to 29.7.0 and typescript to 5.3.3

- Dockerfile
> build: update label and improvements to Dockerfile

- src/stateMachines/ciraConfiguration.ts
> refactor: cira configuration

- src/stateMachines/maintenance/syncTime.test.ts
- src/stateMachines/maintenance/syncTime.ts
> refactor: adjust types for syncTime responses

- src/stateMachines/maintenance/syncIP.ts
> refactor: ensure PUT_ETHERNET doesnt fail when syncing ip

- package.json
> build: add npm run build command

- package-lock.json
- package.json
- src/Configurator.ts
> fix: update build tasks

- data/init.sql
> fix(db): adds create database to init.sql

- .releaserc.json
> ci: update release process for routine updates

- package-lock.json
> build(deps): update ws dependency to version 7.5.10

- .github/workflows/node.js.yml
- .github/workflows/semantic.yml
> ci: update toplevel permissions

- src/stateMachines/ciraConfiguration.test.ts
- src/stateMachines/ciraConfiguration.ts
> fix: cira connection in static ip environment

- .github/workflows/trivy-scan.yml
> ci: upload trivy result scan

- .devcontainer/devcontainer.json
- README.md
- [ N/A ] Unit Tests have been added for new changes
- [ N/A ] API tests have been updated if applicable
- [ N/A ] All commented code has been removed
- [ N/A ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.
Add support for devcontainer in vscode.
Feature device-management-toolkit/cloud-deployment#383
> feat(docker): add support for devcontainer

- .github/workflows/docker-image.yml
- .github/workflows/release.yml
- .releaserc.json
- docker-compose.yml
> feat: enable multiarch build

- .releaserc.json
https://github.com/device-management-toolkit/cloud-deployment/issues/401
> build: adds intel/device-mgmt-toolkit-rps docker tag to release

- src/Validator.ts
- src/stateMachines/activation.test.ts
- src/stateMachines/activation.ts
> feat: Secure host based configuration acm

- README.md
> docs: correct status badge urls in readme

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/config.yml
> docs: update issue template

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/config.yml
> docs: add name to issue template

- swagger.yaml
> docs: add swagger yaml to repo

- data/init.sql
> refactor: enforce unique address and port per tenant
